packages:
  - examples/*
  - '!examples/vue-*-admin-main'
  - packages/form/*
  - packages/preferences/*
  - packages/layout/*
  - packages/table/*
  - internal/*

# 包名映射
# packages/preferences/core   -> @admin-core/preferences       核心包（框架无关）
# packages/preferences/vue    -> @admin-core/preferences-vue   Vue 实现
# packages/preferences/react  -> @admin-core/preferences-react React 实现
#
# core 包内部结构:
# - types/      类型定义
# - constants/  常量配置（主题预设、布局常量、默认配置）
# - utils/      共享工具（颜色生成、缓存管理、深度合并、CSS变量操作）
# - styles/     样式系统（CSS变量、动画、Tailwind v4预设）
# - locales/    国际化（中文/英文）
# - adapters/   UI适配器（Ant Design、Element Plus、Naive UI、shadcn/ui）

catalog:
  '@changesets/cli': ^2.29.7
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/lucide': ^1.2.86
  '@vueuse/core': ^13.4.0
  '@types/culori': ^4.0.1
  '@types/node': ^25.0.9
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@types/react-test-renderer': ^19.1.0
  '@typescript-eslint/eslint-plugin': ^8.42.0
  '@typescript-eslint/parser': ^8.42.0
  '@vitejs/plugin-react': ^5.1.2
  '@vitejs/plugin-vue': ^6.0.3
  '@vue/test-utils': ^2.4.6
  '@vitest/coverage-v8': ^4.0.17
  ant-design-vue: ^4.2.6
  antd: ^6.2.1
  culori: ^4.0.2
  element-plus: ^2.13.1
  eslint: ^9.39.2
  eslint-plugin-react: ^7.37.1
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-vue: ^10.7.0
  vue-eslint-parser: ^10.2.0
  glob: ^13.0.0
  husky: ^9.1.7
  jsdom: ^26.1.0
  lint-staged: ^16.2.7
  naive-ui: ^2.43.2
  prettier: ^3.6.2
  react: ^19.2.4
  react-dom: ^19.2.4
  react-test-renderer: ^19.2.4
  rimraf: ^6.0.1
  rollup-plugin-visualizer: ^6.0.3
  tailwindcss: ^4.1.10
  tsup: ^8.5.1
  tsx: ^4.19.0
  turbo: ^2.5.6
  theme-colors: ^0.1.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vue-i18n: ^11.0.0
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.17
  vue: ^3.5.27
  vue-router: ^4.5.0
  vue-tsc: ^3.2.3
  vxe-pc-ui: ^4.3.36
  vxe-table: ^4.12.6
  zod: ^4.1.5
