export {
  // 类型
  type BasicLayoutProps,
  type LayoutEvents,
  type LayoutSlotName,
  type LayoutState,
  type LayoutContext,
  type LayoutComputed,
  type LayoutVisibility,
  type LayoutDisabled,
  type LayoutWidgetConfig,
  type MenuItem,
  type TabItem,
  type BreadcrumbItem,
  type UserInfo,
  type NotificationItem,
  type AutoTabConfig,
  type AutoBreadcrumbConfig,
  type ThemeConfig,
  type WatermarkConfig,
  type LockScreenConfig,
  type CheckUpdatesConfig,
  type RouterConfig,
  type RouterNavigateFunction,
  // 常量
  DEFAULT_LAYOUT_CONFIG,
  DEFAULT_HEADER_CONFIG,
  DEFAULT_SIDEBAR_CONFIG,
  DEFAULT_TABBAR_CONFIG,
  DEFAULT_FOOTER_CONFIG,
  DEFAULT_BREADCRUMB_CONFIG,
  DEFAULT_NAVIGATION_CONFIG,
  DEFAULT_PANEL_CONFIG,
  DEFAULT_LOGO_CONFIG,
  DEFAULT_COPYRIGHT_CONFIG,
  DEFAULT_WIDGET_CONFIG,
  DEFAULT_VISIBILITY_CONFIG,
  DEFAULT_DISABLED_CONFIG,
  DEFAULT_CONTENT_CONFIG,
  DEFAULT_LAYOUT_STATE,
  DEFAULT_TRANSITION_CONFIG,
  DEFAULT_SHORTCUT_KEYS_CONFIG,
  DEFAULT_THEME_CONFIG,
  DEFAULT_WATERMARK_CONFIG,
  DEFAULT_LOCK_SCREEN_CONFIG,
  DEFAULT_CHECK_UPDATES_CONFIG,
  DEFAULT_AUTO_TAB_CONFIG,
  DEFAULT_AUTO_BREADCRUMB_CONFIG,
  LAYOUT_CATEGORIES,
  CSS_VAR_NAMES,
  ANIMATION_DURATION,
  HEADER_TRIGGER_DISTANCE,
  BREAKPOINTS,
  // 工具函数
  isLayoutInCategory,
  isFullContentLayout,
  isSidebarMixedNavLayout,
  isHeaderNavLayout,
  isMixedNavLayout,
  isHeaderMixedNavLayout,
  shouldShowSidebar,
  shouldShowHeader,
  calculateSidebarWidth,
  calculateHeaderHeight,
  calculateTabbarHeight,
  calculateFooterHeight,
  calculatePanelWidth,
  calculateLayoutComputed,
  generateCSSVariables,
  findMenuByKey,
  getMenuId,
  getMenuPath,
  flattenMenus,
  filterHiddenMenus,
  clearMenuCaches,
  mergeConfig,
  // 自动标签/面包屑
  TabManager,
  generateBreadcrumbsFromMenus,
  findMenuByPath,
  getMenuPathByPath,
  // Preferences 深度集成工具函数
  mapPreferencesToLayoutProps,
  generateThemeCSSVariables,
  generateThemeClasses,
  generateWatermarkStyle,
  generateWatermarkContent,
  shouldShowLockScreen,
  createAutoLockTimer,
  createCheckUpdatesTimer,
  getResolvedLayoutProps,
  generateAllCSSVariables,
  // 国际化
  createI18n,
  builtinLocales,
  zhCN,
  enUS,
  type LayoutLocale,
  type SupportedLocale,
  type I18nInstance,
  // 样式
  layoutThemeTokens,
  tailwindThemeCSS,
  layoutBaseCSS,
  layoutUtilitiesCSS,
  layoutFullCSS,
  // 路由辅助类型
  type RouteModule,
  type RouteRecordStringComponent,
} from '@admin-core/layout';

export * from './layout-state-common';
